---
# tasks file for ssh_config_from_inventory
- name: Make sure ssh_configs_dir is created
  file:
    path: "{{ ssh_configs_dir }}"
    state: directory
    mode: 0755
- name: create a local config file
  template:
    src: "ssh_config.j2"
    dest: "{{ ssh_configs_dir }}/ssh_config_{{inv_group}}"
  delegate_to: localhost
  become: "False"
- name: Merge the config with your local SSH config
  blockinfile:
    block: "{{ lookup('file', '{{ ssh_configs_dir }}/ssh_config_{{inv_group}}') }}"
    dest: "{{ ssh_config_file }}"
    backup: yes
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ssh_config_from_inventory) {{inv_group}}"
  delegate_to: localhost
  become: "False"
